name: precept_backend
description: Common declarations for Precept backend implementations
version: 0.0.1
author: David Sowerby
homepage: https://www.preceptblog.co.uk/

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.0
  graphql: ^5.0.0
  json_annotation: ^4.1.0
  meta: ^1.7.0
  precept_script:
    path: ../precept_script

dev_dependencies:
  test:
  mocktail: ^0.1.4
  build_runner:
  json_serializable: ^5.0.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec


