name: takkan_script
description: A script for creating Flutter applications.
version: 0.0.1
homepage: https://takkan.org

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  json_annotation: ^4.5.0
  logger: ^1.1.0
  validators: ^3.0.0
  get_it: ^7.2.0
  equatable: ^2.0.3
  characters: ^1.2.1


dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  collection: ^1.16.0
  build_runner: ^2.1.10
  json_serializable: ^6.2.0
  takkan_medley_script:
    path: ../takkan_medley_script
