name: takkan_back4app_generator
description: Generate Back4App server code from a Takkan Schema.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.0 <4.0.0'


dependencies:
  dio: ^5.2.1+1
  characters: ^1.2.0
  json_annotation: ^4.5.0
  equatable: ^2.0.3
  takkan_schema: ^0.1.0
  takkan_back4app_client: ^0.0.1
  takkan_backend: ^0.0.1


dev_dependencies:
  path: ^1.8.1
  lints: ^2.1.1
  mocktail: ^0.3.0
  test:
  takkan_medley_orchestrator: ^0.0.1