name: takkan_backend
description: Common declarations for Takkan backend implementations
version: 0.0.1
homepage: https://takkan.org/

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dio: ^5.2.1+1
  graphql: ^5.0.0
  json_annotation: ^4.4.0
  meta: ^1.7.0
  takkan_script: ^0.0.1
  takkan_schema: ^0.1.0


dev_dependencies:
  test:
  mocktail: ^0.3.0
  build_runner:
  json_serializable: ^6.1.4
  http_mock_adapter: ^0.4.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec


